sources: 
  - name: grant-ships
    handler: 
      graphql: 
        # endpoint: https://indexer.bigdevenergy.link/f61c4de/v1/graphql
        endpoint: http://localhost:8080/v1/graphql
        # endpoint: https://{context.apiEndpoint:api.studio.thegraph.com/query/41101/grant-ships-arb/version/latest}
  # - name: gs-voting
  #   handler: 
  #     graphql: 
  #       # endpoint: http://localhost:8080/v1/graphql
  #       endpoint: https://indexer.bigdevenergy.link/d18cda9/v1/graphql
documents: 
  # - './src/**/*.graphql'
  - './src/graphql/newQueries/**/*.graphql'
