sources: 
  - name: grant-ships
    handler: 
      graphql: 
        endpoint: https://indexer.dev.hyperindex.xyz/6410aa4/v1/graphql
        # endpoint: http://localhost:8080/v1/graphql
documents: 
  # - './src/**/*.graphql'
  - './src/graphql/newQueries/**/*.graphql'
