sources: 
  - name: grant-ships
    handler: 
      graphql: 
        # endpoint: https://indexer.bigdevenergy.link/3a96753/v1/graphql
        endpoint: http://localhost:8080/v1/graphql
documents: 
  # - './src/**/*.graphql'
  - './src/graphql/newQueries/**/*.graphql'
