sources: 
  - name: grant-ships
    handler: 
      graphql: 
        endpoint: https://{context.apiEndpoint:api.studio.thegraph.com/query/41101/grant-ships-arb/version/latest}
  - name: gs-voting
    handler: 
      graphql: 
        endpoint: https://indexer.bigdevenergy.link/6b18ba8/v1/graphql
documents: 
  - './src/**/*.graphql'
